# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        cd cli
        chmod +x ../build/build.sh

        mkdir -p release
        echo "execute compile"
        export CGO_ENABLED=0
        export GOARCH=amd64
        export GOOS=linux
        ../build/build.sh
        echo "execute completely"
        ls
        mv ./cfs-cli ./release/cfs-cli-amd64

        echo "execute arm64"
        export CGO_ENABLED=0
        export GOARCH=arm64
        export GOOS=linux
        echo "execute compile"
        ../build/build.sh
        echo "execute completely"
        ls
        mv ./cfs-cli ./release/cfs-cli-arm64

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cli/release/cfs-cli-*
        tag: ${{ github.ref }}
        overwrite: true
        body: "multi architecture release"
        file_glob: true